# Generated by Django 4.2.6 on 2023-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=0, max_length=10, unique=True),
        ),
    ]
