# Generated by Django 4.2.6 on 2023-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
