# Generated by Django 4.2.6 on 2023-11-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='warnings',
            field=models.BooleanField(default=False),
        ),
    ]
