# Generated by Django 4.2.6 on 2023-12-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_users_latitude_users_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nearestStation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
