# Generated by Django 4.2.6 on 2023-12-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_users_neareststation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='warnings',
        ),
    ]
