# Generated by Django 4.2.6 on 2023-12-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='stationCode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
