# Generated by Django 4.1.6 on 2024-01-31 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_users_stationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pings',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=5, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
