# Generated by Django 4.1.6 on 2024-02-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pings',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
