# Generated by Django 4.1.6 on 2024-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_pings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pings',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
